### ISSUE TITLE
left shift count >= width of type

### ISSUE THREAD

**Issue by board707** [marcmerlin/Framebuffer_GFX#3]
In the Framebuffer_GFX.cpp line 152:
```
return (uint32_t)(c.r<<16) + (uint32_t)(c.g<<8) + (uint32_t)c.b;
```
you used incorrect cast to uint32_t

The expression
```
(uint32_t)(c.r<<16)
```
means that you make left shift FIRST, compute the result, using the type of the c.r variable and only after that (and perhaps after truncating the result to uint16 on AVR controllers) - casting it to uint32_t.

The correct syntax that prevent the truncation is:
```
((uint32_t)c.r<<16)
```
so you make casting FIRST and than shift the uint32_t value.

**Comment by marcmerlin** [comment]
You are absolutely correct, good catch. I think I got away with the bug since the chips I use are all 32bit now, but this is absolutely a bug I need to fix.
Out of curiosity, what were you running on when you found this?

**Comment by marcmerlin** [comment]
If you'd like to submit a PR to get credit for the fix, feel free, otherwise I'll just patch the source.

**Comment by board707** [comment]
> good catch

It was just a compiler warning :)

> Out of curiosity, what were you running on when you found this?

Try to help one guy to build [14Channel Spectrum analyzer](https://github.com/donnersm/14ChannelAnalyzerV2.0), which used your Framebuffer on Arduino Mega board.

I don’t think it’s worth creating PR for the sake of one line....

**Comment by board707** [comment]
By the way, I thought to use your Framebuffer when working with LED matrices (I wrote my small library), but I didn’t figure out how to replace AdafruitGFX with Framebuffer.

**Comment by marcmerlin** [comment]
Arduino Mega, they still exist? :)
(not to make excuses for my bad code, that needed to be fixed, but I'm a bit surprised when new projects use $30+ arduino boards with 16bit CPUs when an ESP32 is $5 or so)

For hardware support, I suppose you've already seen 
http://marc.merlins.org/perso/arduino/post_2020-03-16_Framebuffer_GFX_-Choosing-between-its-3-2D-APIs_-FastLED-XY_-NeoMatrix_-and-LEDMatrix_-and-detail-of-its-many-supported-hardware-backends.html

I did actually write my own interrupt driver for LED matrices, see http://marc.merlins.org/perso/arduino/post_2015-01-06_Driver-for-direct-driving-single-to-3-color-LED-Matrices-with-software-PWM.html 
but I never made a framebuffer:::GFX backend for those simply because they are too small and too low resolution in color depth (like the one I just mentioned is only 4bits per color), so I simply use Adafruit::GFX on them (although by that I mean I've stopped using that hardware many years ago)

**Comment by board707** [comment]
> I'm a bit surprised when new projects use $30+ arduino boards with 16bit CPUs when an ESP32 is $5 or so

Yes, I am personally prefer to use STM32 or RP2040 mcus, but this project is not mine :)
My LED matrix library is [DMD_STM32](https://github.com/board707/DMD_STM32). It can drive up to 16 panels of 64x32 HUB75 RGB, but only with 16 bit (565) color, because it based on AdafruitGFX graphic library.
Thank you.
